name: rso
description: Ruta Sin Obstáculos - Sistema de Reporte de Invasión al Espacio Público
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  
  # Manejo de estado
  provider: ^6.0.5
  
  # Imágenes
  image_picker: ^1.0.5
  
  # Geolocalización
  geolocator: ^10.1.0
  
  # Para obtener direcciones a partir de coordenadas
  geocoding: ^2.1.1
  
  # Íconos adicionales
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets (para imágenes locales si las tienes)
  # assets:
  #   - assets/images/